"""initial schema

Revision ID: ad27bde68b40
Revises: 
Create Date: 2026-08-08 13:14:58.032857
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

revision = 'ad27bde68b40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('bbox', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('centroid', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_cities_bbox', 'cities', ['bbox'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_cities_centroid', 'cities', ['centroid'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_cities_slug'), 'cities', ['slug'], unique=True)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('records', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_source'), 'ingestion_runs', ['source'], unique=False)
    op.create_geospatial_table('road_segments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('osm_way_id', sa.BigInteger(), nullable=True),
    sa.Column('u_node', sa.BigInteger(), nullable=True),
    sa.Column('v_node', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('highway_class', sa.Text(), nullable=True),
    sa.Column('length_m', sa.Float(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('elev_mean', sa.Float(), nullable=True),
    sa.Column('slope_mean', sa.Float(), nullable=True),
    sa.Column('hand_min', sa.Float(), nullable=True),
    sa.Column('hand_mean', sa.Float(), nullable=True),
    sa.Column('wofs_freq_max', sa.Float(), nullable=True),
    sa.Column('dist_to_drainage_m', sa.Float(), nullable=True),
    sa.Column('crosses_drainage', sa.Boolean(), nullable=True),
    sa.Column('susceptibility', sa.Float(), nullable=True),
    sa.Column('susceptibility_pctile', sa.Float(), nullable=True),
    sa.Column('features_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_road_segments_geom', 'road_segments', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_road_segments_city_id'), 'road_segments', ['city_id'], unique=False)
    op.create_index('ix_road_segments_city_pctile', 'road_segments', ['city_id', 'susceptibility_pctile'], unique=False)
    op.create_index(op.f('ix_road_segments_highway_class'), 'road_segments', ['highway_class'], unique=False)
    op.create_index('ix_road_segments_osm_way', 'road_segments', ['osm_way_id'], unique=False)
    op.create_geospatial_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('corridor', Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('corridor_name', sa.Text(), nullable=True),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('webhook_url', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_subscriptions_corridor', 'subscriptions', ['corridor'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_subscriptions_active'), 'subscriptions', ['active'], unique=False)
    op.create_index(op.f('ix_subscriptions_email'), 'subscriptions', ['email'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.BigInteger(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['road_segments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_subscription_id'), 'alerts', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_alerts_triggered_at'), 'alerts', ['triggered_at'], unique=False)
    op.create_table('segment_risk',
    sa.Column('segment_id', sa.BigInteger(), nullable=False),
    sa.Column('valid_date', sa.Date(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_band', sa.String(length=16), nullable=False),
    sa.Column('rain_7d_mm', sa.Float(), nullable=True),
    sa.Column('rain_24h_forecast_mm', sa.Float(), nullable=True),
    sa.Column('contributions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['road_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('segment_id', 'valid_date')
    )
    op.create_index('ix_segment_risk_date_score', 'segment_risk', ['valid_date', 'risk_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_segment_risk_date_score', table_name='segment_risk')
    op.drop_table('segment_risk')
    op.drop_index(op.f('ix_alerts_triggered_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_subscription_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_subscriptions_email'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_active'), table_name='subscriptions')
    op.drop_geospatial_index('idx_subscriptions_corridor', table_name='subscriptions', postgresql_using='gist', column_name='corridor')
    op.drop_geospatial_table('subscriptions')
    op.drop_index('ix_road_segments_osm_way', table_name='road_segments')
    op.drop_index(op.f('ix_road_segments_highway_class'), table_name='road_segments')
    op.drop_index('ix_road_segments_city_pctile', table_name='road_segments')
    op.drop_index(op.f('ix_road_segments_city_id'), table_name='road_segments')
    op.drop_geospatial_index('idx_road_segments_geom', table_name='road_segments', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('road_segments')
    op.drop_index(op.f('ix_ingestion_runs_source'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_cities_slug'), table_name='cities')
    op.drop_geospatial_index('idx_cities_centroid', table_name='cities', postgresql_using='gist', column_name='centroid')
    op.drop_geospatial_index('idx_cities_bbox', table_name='cities', postgresql_using='gist', column_name='bbox')
    op.drop_geospatial_table('cities')
    # ### end Alembic commands ###
